name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: step1
      id: step1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: step1
        setup-command: make
        command: "./tester step1"
        timeout: 10
        max-score: 1
    - name: step2
      id: step2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: step2
        setup-command: make
        command: "./tester step2"
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        STEP1_RESULTS: "${{steps.step1.outputs.result}}"
        STEP2_RESULTS: "${{steps.step2.outputs.result}}"
      with:
        runners: step1,step2
